### ISSUE TITLE
The module should not load implicitly defined default config file 

### ISSUE THREAD

**Issue by serge-m** [phha/click_config_file#1]
## Observed behaviour:
Given a main module
```python
import json
import click
import click_config_file


def json_config_provider(file_path: str, cmd_name: str):
    return _load_json_as_config(file_path)[cmd_name]

def _load_json_as_config(file_path: str) -> dict:
    with open(file_path) as config_data:
        return json.load(config_data)

@click.command()
@click.option("--logging", type=dict, default=123)
@click_config_file.configuration_option(provider=json_config_provider)
def main(logging):
  print(logging)


if __name__ == '__main__':
    main()
```
 
and '~/.config/test_config.py/config' doesn't exist.
I run it without arguments. 
and I get 

```
~/envs/prtpy36/bin/python ~/test_config.py
Usage: test_config.py [OPTIONS]

Error: Error reading configuration file: [Errno 2] No such file or directory: '~/.config/test_config.py/config'
```

## Expected behaviour
The code must print `123`

Logic: config file is not specified, therefore one should use defaults.

## Possible solution
in `configuration_option` we introduce a new boolean parameter `use_default_config_path`. If it is true then we are trying to load default config, otherwise we don't update context.

What do you think? I could implement it if you agree.

**Comment by serge-m** [comment]
@phha ?

**Comment by phha** [comment]
Hi @serge-m,

thank you for bringing this to my attention.

The error you are seeing is actually an exception that is bubbling up from your custom provider, not from click_config_file itself.

A possible solution would be to check whether the file exists inside configuration_option and only call the provider in case it does. However I'm reluctant to do this for the following reasons:

1. Even if the file does not exist, the custom provider might want to perform some action (e.g. create the file and populate it with defaults)

2. The configuration provider might not actually operate on a file basis, but could potentially source the configuration through some other mechanism, eg. a database or some API. If I check for existance of the file such a provider will no longer work.

3. Even if the file does exist the provider could still throw an error, such as when parsing fails.

Therefore I prefer error handling to be done inside the provider.

I also don't want to add another parameter, since it's somewhat redundant. configuration_option already inherits the `exists` parameter from click.File which will configuration_option to fail if the path is not found. And of course the default path can be overridden as well.

The documentation on custom providers is very brief and does not address error handling inside the provider. This applies to missing files as well as other errors that might pop up inside the provider, e.g. parsing errors. I will use this ticket to track the extension of the documentation regarding this topic.

For your specific issue I would suggest you catch the exception inside the provider and return an empty dict in case of error.

```python
def _load_json_as_config(file_path: str) -> dict:
    with open(file_path) as config_data:
        try:
                return json.load(config_data)
        except FileNotFoundError:
                return {}
```

**Comment by serge-m** [comment]
The problem is that `provider` doesn't know how to handle the missing file. There are two situations:

* we run the script with `--config /home/<user>/.config/test_config.py/config` and the file is missing. In this case the provider have to treat is as an error. The user has to know that file is missing because he  **explicitly** asked about loading parameters from the script. The failure must be processed explicitly.

* we run script without `--config` and `click_config_file` pass default value `/home/<user>/.config/test_config.py/config` to the provider. In this case the provider has to return a value defined in  `@click.option("--logging", type=dict, default=123)` and don't fail. 

I could parse the path and do something like 
```python
if file_is_missing:
  if re.match("/home/blabla/.*\.config.*/blabla"):
    # use default values
  else:
    raise ConfigFileNotFound()
```
but it seems like a really bad solution because I threat different config paths differently -> that is not transparent for the user.

Maybe there is another way of distinguishing those cases?
@phha

**Comment by serge-m** [comment]
>    Even if the file does not exist, the custom provider might want to perform some action (e.g. create the file and populate it with defaults)

Good. But how can provider understand if it should do it? The user could just make a typo in the file path.

>    The configuration provider might not actually operate on a file basis, but could potentially source the configuration through some other mechanism, eg. a database or some API. If I check for existance of the file such a provider will no longer work.

Exactly! your module must not check for existence. It must not even assume anything about existence! The provider knows how to handle existence and must take care. Maybe if `--config` is not specified I sould load `./config.sqlite ` in the current directory. It is up to provider to decide.

>    Even if the file does exist the provider could still throw an error, such as when parsing fails.

Sure. But I don't see how it is connected to the bug I describe.

> Therefore I prefer error handling to be done inside the provider.

Me too. But I don't understand how to do it properly.

> And of course the default path can be overridden as well.

How to override default path? So that it `=None` for example? That actually would solve my problem.


In the code I see
```python
            default_value = os.path.join(
                click.get_app_dir(cmd_name), config_file_name)
            param.default = default_value
            if not value:
                value = default_value
```
And there is no way to set `default_value`. If there would be `default_value` parameter I could pass there a special value, like `False` and in the provider I can check 
```python
if  file_path is False:
  return {}
else:
  # try to open
  # raise if not found
```
So how about an extra parameter? :wink:

**Comment by serge-m** [comment]
I managed to do what I want. Maybe it will be helpful for anyone else:

test_config.py:
```python
import json

import click
import click_config_file

FLAG_CONFIG_NOT_SPECIFIED = 'BLA/////////////////%%%%%%%%%%%%~~~~~~~~~~~~~~~~'


def json_config_provider(file_path: str, cmd_name: str):
    if file_path.endswith(FLAG_CONFIG_NOT_SPECIFIED):
        return {}
    return _load_json_as_config(file_path)[cmd_name]


def _load_json_as_config(file_path: str) -> dict:
    try:
        with open(file_path) as config_data:
            return json.load(config_data)
    except Exception as e:
        raise Exception("Unable to load json config " + file_path) from e


@click.command()
@click.option("--logging", type=str, default="default-from-option")
@click_config_file.configuration_option(config_file_name=FLAG_CONFIG_NOT_SPECIFIED, provider=json_config_provider)
def main(logging):
    print(logging)


if __name__ == '__main__':
    main()
```

existing.json:
```json
{
  "logging": "from-config-upper-level",
  "test_config.py": {
    "logging": "from-config-nested"
  }
}
```

Usage 1:
```
test_config.py --config ./non-existent-config
Usage: test_config.py [OPTIONS]

Error: Error reading configuration file: Unable to load json config ./non-existent-config

Process finished with exit code 2
```

Usage 2
```
test_config.py --config ./existing.json
from-config-nested

Process finished with exit code 0
```

Usage 3
```
test_config.py
default-from-option

Process finished with exit code 0
```

----------------------
To get the top-level value one has to ignore cmd_name parameter:
```python

def json_config_provider(file_path: str, cmd_name: str):
    if file_path.endswith(FLAG_CONFIG_NOT_SPECIFIED):
        return {}
    return _load_json_as_config(file_path)
```

Still dirty of course

**Comment by phha** [comment]
Good point about the provider needing a way to distinguish between explicit and default path. Your solution is fine as a workaround, but I agree that this should be fixed inside configuration_option.

**Comment by phha** [comment]
> How to override default path? So that it =None for example? That actually would solve my problem.

You can set it like the default value of any other click option with `configuration_option(default='foo')`

You just can't set it to `False` or `None` because then it will be overwritten by the default value inside configuration_option.

I think therein lies the problem. Maybe it would be more appropriate to let the provider determine the default value.

**Comment by rcoup** [comment]
One common pattern here is to use an `object` instance to indicate something truthy that isn't boolean or None.

eg.
```
NOTSET=object()

def json_config_provider(file_path, cmd_name):
    if file_path is NOTSET:
        return {}
    return _load_json_as_config(file_path)[cmd_name]

@click.command()
@click.option("--logging", type=str, default="default-from-option")
@click_config_file.configuration_option(config_file_name=NOTSET, provider=json_config_provider)
def main(logging):
    print(logging)
```

**Comment by ltalirz** [comment]
@rcoup your suggestion looks reasonable but it doesn't work out of the box here, since `click_config_file` mangles the `config_file_name` (converting it to an absolute path, etc.) and won't be happy with being passed an `object()`.

I believe the underlying issue here is that there are (at least) two possible variants for the purpose of a "config file option" in a CLI:

  1. The CLI should always look for a config file. The `--config` option is just for *changing the name/path of the config file* (this is what `click_config_file.configuration_option` currently implements).
  2. The CLI should *only* look for a config file, if the `--config` option is specified (this is what @serge-m and me are interested in).

In the second variant, it is not be the job of the `config_file_provider` to figure out whether the option was specified. Rather, it is the job of the option to call the `config_file_provider` only when needed.

Since the two variants serve different use cases, why not provide two types of options for them?
Most of the code can be shared - variant 2 would be the "base"; simply have no default for the config file name and would call the `config_file_provider` only if a value for the `--config` option is provided.

Variant 1 would use the code of variant 2 but set a default value for the config file name.
