### ISSUE TITLE
config options for commands?

### ISSUE THREAD

**Issue by ws1088** [phha/click_config_file#10]
Is it possible to specify options for main and test in a single config file?

```import click
import click_config_file

@click.group()
@click.option('--name', help='A name')
@click_config_file.configuration_option()
def main(name):
    print('main: {}'.format(name))
    return 0

@click.command()
@click.option('--name', help='A name')
@click_config_file.configuration_option()
def test(name):
    print('test: {}'.format(name))
    pass

main.add_command(test)
if __name__ == '__main__':
    main()
```

**Comment by phha** [comment]
Do you want the values for name to be the same or different?

If you want it to be the same, you have several options.

When using implicit config file lookup:
```python
@click.group()
@click.option('--name', help='A name')
@click_config_file.configuration_option(cmd_name='main')
def main(name):
    print('main: {}'.format(name))
    return 0

@main.command()
@click.option('--name', help='A name')
@click_config_file.configuration_option(cmd_name='main')
def test(name):
    print('test: {}'.format(name))
    pass
```

And put your config in `~/.config/main/config`, or whatever is appropriate for your OS

If you are passing the configuration option as a cli option, you need to do`main.py --config my.cfg test --config my.cfg`, because [click strictly separates parameters between commands and subcommands](https://click.palletsprojects.com/en/7.x/commands/#passing-parameters).

As a third option, you can [pass the context from your main command to your subcommands](https://click.palletsprojects.com/en/7.x/commands/#nested-handling-and-contexts).

If you want to define separate values for your subcommands, you can define a section name for each command:

```python
main_provider=click_config_file.configobj_provider(section='main')
@click.group()
@click.option('--name', help='A name')
@click_config_file.configuration_option(provider=main_provider, cmd_name='main')
def main(name):
    print('main: {}'.format(name))
    return 0

test_provider=click_config_file.configobj_provider(section='test')
@main.command()
@click.option('--name', show_default=True)
@click_config_file.configuration_option(provider=test_provider, cmd_name='main')
def test(name):
    print('test: {}'.format(name))
    pass
```
 And have a config file like this:
```
[main]
name="Foo"

[test]
name="Bar"
```

**Comment by phha** [comment]
Closing this as answered
